id: IE756469E
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T20:38:06.335282'
last_modified: '2022-05-30T20:38:06.335312'
parser: null
source_metadata:
  title: Dzong-ngön Pema Tukchok Dorje
  language: en
  description: 'Texts by and about Dzong-ngön Pema Tukchok Dorje (rdzong sngon padma
    thugs mchog rdo rje), the incarnation of Dola Jigme Kalzang:'
  volume:
    fF31F:
      title: A Simple Method of Transference for Helpless Animals
      base_file: fF31F.txt
      order: 1
      parent: Transference
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
